package com.syswin.pipeline.db.model;

import java.util.ArrayList;
import java.util.List;

public class BrowseRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public BrowseRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBrowseIdIsNull() {
            addCriterion("browse_id is null");
            return (Criteria) this;
        }

        public Criteria andBrowseIdIsNotNull() {
            addCriterion("browse_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrowseIdEqualTo(Long value) {
            addCriterion("browse_id =", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdNotEqualTo(Long value) {
            addCriterion("browse_id <>", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdGreaterThan(Long value) {
            addCriterion("browse_id >", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("browse_id >=", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdLessThan(Long value) {
            addCriterion("browse_id <", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdLessThanOrEqualTo(Long value) {
            addCriterion("browse_id <=", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdIn(List<Long> values) {
            addCriterion("browse_id in", values, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdNotIn(List<Long> values) {
            addCriterion("browse_id not in", values, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdBetween(Long value1, Long value2) {
            addCriterion("browse_id between", value1, value2, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdNotBetween(Long value1, Long value2) {
            addCriterion("browse_id not between", value1, value2, "browseId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andContentIdIsNull() {
            addCriterion("content_id is null");
            return (Criteria) this;
        }

        public Criteria andContentIdIsNotNull() {
            addCriterion("content_id is not null");
            return (Criteria) this;
        }

        public Criteria andContentIdEqualTo(Long value) {
            addCriterion("content_id =", value, "contentId");
            return (Criteria) this;
        }

        public Criteria andContentIdNotEqualTo(Long value) {
            addCriterion("content_id <>", value, "contentId");
            return (Criteria) this;
        }

        public Criteria andContentIdGreaterThan(Long value) {
            addCriterion("content_id >", value, "contentId");
            return (Criteria) this;
        }

        public Criteria andContentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("content_id >=", value, "contentId");
            return (Criteria) this;
        }

        public Criteria andContentIdLessThan(Long value) {
            addCriterion("content_id <", value, "contentId");
            return (Criteria) this;
        }

        public Criteria andContentIdLessThanOrEqualTo(Long value) {
            addCriterion("content_id <=", value, "contentId");
            return (Criteria) this;
        }

        public Criteria andContentIdIn(List<Long> values) {
            addCriterion("content_id in", values, "contentId");
            return (Criteria) this;
        }

        public Criteria andContentIdNotIn(List<Long> values) {
            addCriterion("content_id not in", values, "contentId");
            return (Criteria) this;
        }

        public Criteria andContentIdBetween(Long value1, Long value2) {
            addCriterion("content_id between", value1, value2, "contentId");
            return (Criteria) this;
        }

        public Criteria andContentIdNotBetween(Long value1, Long value2) {
            addCriterion("content_id not between", value1, value2, "contentId");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeIsNull() {
            addCriterion("browse_time is null");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeIsNotNull() {
            addCriterion("browse_time is not null");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeEqualTo(Integer value) {
            addCriterion("browse_time =", value, "browseTime");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeNotEqualTo(Integer value) {
            addCriterion("browse_time <>", value, "browseTime");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeGreaterThan(Integer value) {
            addCriterion("browse_time >", value, "browseTime");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("browse_time >=", value, "browseTime");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeLessThan(Integer value) {
            addCriterion("browse_time <", value, "browseTime");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeLessThanOrEqualTo(Integer value) {
            addCriterion("browse_time <=", value, "browseTime");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeIn(List<Integer> values) {
            addCriterion("browse_time in", values, "browseTime");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeNotIn(List<Integer> values) {
            addCriterion("browse_time not in", values, "browseTime");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeBetween(Integer value1, Integer value2) {
            addCriterion("browse_time between", value1, value2, "browseTime");
            return (Criteria) this;
        }

        public Criteria andBrowseTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("browse_time not between", value1, value2, "browseTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table browse_record
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 17 09:25:39 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table browse_record
     *
     * @mbg.generated Thu Jan 17 09:25:39 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}